OnlineStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core.Contracts;
using OnlineStore.Infrastructure.Data.Models;
using static OnlineStore.Core.Constants.MessageConstants;

namespace OnlineStore.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService cartService;
        private readonly IComicService comicService;

        public CartController(ICartService cartService,
            IComicService comicService)
        {
            this.cartService = cartService;
            this.comicService = comicService;
        }

        public async Task<IActionResult> Details()
        {
            Cart cart = new Cart();

            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            cart = await cartService.GetCartByUserId(email);

            return View(cart);
        }

        public async Task<IActionResult> Purchase(int id)
        {
            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            var comic = await comicService.ComicExistsAsync(id);

            if(!comic)
            {
                TempData[UserMessageError] = "Such comic does not exist!";

                return RedirectToAction("All", "Comic");
            }

            Cart cart = await cartService.GetCartByUserId(email);

            var comicInCart = await cartService.ComicExistsInCart(cart, id);

            if (comicInCart)
            {
                TempData[UserMessageError] = "Comic already in cart!";

                return RedirectToAction("All", "Comic");
            }
            await cartService.Add(cart, id);

            TempData[UserMessageSuccess] = "Comic added to cart!";

            return RedirectToAction("All", "Comic");
        }

        public async Task<IActionResult> Remove(int id)
        {
            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            Cart cart = await cartService.GetCartByUserId(email);

            var comicInCart = await cartService.ComicExistsInCart(cart, id);

            if (!comicInCart)
            {
                TempData[UserMessageError] = "No such comic in the cart!";

                return RedirectToAction("All", "Comic");
            }

            await cartService.Remove(cart, id);

            TempData[UserMessageSuccess] = "Comic removed from cart!";

            return RedirectToAction("Details");
        }

        public async Task<IActionResult> Order(int id)
        {
            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            var cartExist = await cartService.CartExists(id);

            if (!cartExist)
            {
                TempData[UserMessageError] = "No cart found!";

                return RedirectToAction("All", "Comic");
            }

            Cart cart = await cartService.GetCartByUserId(email);

            if(cart == null || cart.Id != id)
            {
                TempData[UserMessageError] = "No cart found!";
                
                return RedirectToAction("All", "Comic");
            }


            if (cart.Comics.Count == 0)
            {
                TempData[UserMessageError] = "No items in cart!";

                return RedirectToAction("All", "Comic");
            }

            await cartService.EmptyCart(cart.Id);

            TempData[UserMessageSuccess] = "Order completed!";

            return View();
        }

    }
}

OnlineStore/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core.Contracts;
using OnlineStore.Core.Models.Category;
using OnlineStore.Core.Services;
using OnlineStore.Infrastructure.Data.Models;
using static OnlineStore.Core.Constants.MessageConstants;

namespace OnlineStore.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            return View(categories);
        }

        [HttpGet]
        public IActionResult Add()
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            CategoryViewModel model = new CategoryViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CategoryViewModel model)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            if (await categoryService.ValidateCategory(model.Name))
            {
                ModelState.AddModelError(nameof(model.Name), "This Category already exists! Add different one or check all categories.");

                return View(model);
            }

            await categoryService.AddCategoryAsync(model);

            TempData[UserMessageSuccess] = "Category added succesfully!";

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Remove(int id)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            Category? category = categoryService.FindCategory(id);

            if (category == null)
            {
                TempData[UserMessageError] = "No such category!";
                return RedirectToAction("All");
            }

            if (categoryService.CheckIfAnyComicWithGivenCategory(id))
            {
                TempData[UserMessageError] = "There are comics with this category! Remove them first!";

                return RedirectToAction("All");
            }

            await categoryService.RemoveAsync(id);

            TempData[UserMessageSuccess] = "Category removed succesfully!";

            return RedirectToAction("All");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            Category categoryToEdit = categoryService.FindCategory(id);

            if (categoryToEdit == null)
            {
                TempData[UserMessageError] = "No such category!";
                return RedirectToAction("All");
            }

            CategoryViewModel categoryModel = new CategoryViewModel()
            {
                Name = categoryToEdit.Name
            };

            return View(categoryModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CategoryViewModel categoryModel)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            var categoryToEdit = categoryService.FindCategory(id);

            if (categoryToEdit == null)
            {
                return RedirectToAction("All");
            }

            await categoryService.EditCategoryAsync(id, categoryModel);

            TempData[UserMessageSuccess] = "Category edited succesfully!";

            return RedirectToAction("All");
        }
    }
}

OnlineStore/Views/Shared/_ComicDetailsPartial.cshtml
@model ComicAllViewModel
@using OnlineStore.Core.Models.Comic;


<div class="col-md-2">
    <div class="card mb-3">
        <img class="img-thumbnail card-img-top" src="@Model.PhotoUrl" alt="Comic Image">
        <div class="card-body text-center">
            <h4>@Model.Title</h4>
            <h6>Creator: <b>@Model.CreatorName</b></h6>
            <h6>
                Category: <b>@Model.CategoryName</b>
            </h6>

            <h6>
                Price:
                <b>@($"{Model.Price:f2}") BGN</b>
            </h6>
            <br />
            
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Comic" asp-action="Details" asp-route-id="@Model.Id"
                   class="btn btn-warning">Details</a>
            }
            
            @if (this.User.IsInRole("Admin"))
            {
                <p></p>
                <a asp-controller="Comic" asp-action="Edit" asp-route-id="@Model.Id"
                   class="btn btn-warning">Edit</a>
                <a asp-controller="Comic" asp-action="Delete" asp-route-id="@Model.Id"
                   class="btn btn-danger" confirm="Are your sure?">Delete</a>
                <p></p>
            }
            @if (User.Identity.IsAuthenticated)
            {
                <div class="form-inline">
                    <a asp-controller="Cart" asp-action="Purchase" asp-route-id="@Model.Id"
                       class="btn btn-success">Purchase</a>
                </div>
            }
            
        </div>
    </div>
</div>

OnlineStore/Views/Shared/_ComicFormPartial.cshtml
@model AddComicViewModel
@using OnlineStore.Core.Models.Comic;

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" placeholder="Title of the comic">
                <span asp-validation-for="Title" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creator"></label>
                <input asp-for="Creator" class="form-control" placeholder="Creator of the comic">
                <span asp-validation-for="Creator" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="Description of the comic"></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoUrl"></label>
                <input asp-for="PhotoUrl" class="form-control" placeholder="Photo URL">
                <span asp-validation-for="PhotoUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.CategoryId">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
                <br/>
                <a class="btn btn-warning" asp-controller="Creator" asp-action="Add">Add Creator</a>
            </div>
        </form>
    </div>
</div>

OnlineStore/Views/Shared/_Layout.cshtml
@using OnlineStore.Core.Constants;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Panel</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Comic" asp-action="All">All Comics</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Creator" asp-action="All">All Creators</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="All">All Categories</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Comic" asp-action="Add">Add Comic</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Creator" asp-action="Add">Add Creator</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Add">Add Category</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OnlineStore - <a asp-area="" asp-controller="Comic" asp-action="All">All Comics</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if (TempData[MessageConstants.UserMessageSuccess] != null)
    {
        <script defer>
            message.showSuccess('@TempData[MessageConstants.UserMessageSuccess]');
        </script>
    }
    @if (TempData[MessageConstants.UserMessageError] != null)
    {
        <script defer>
            message.showError('@TempData[MessageConstants.UserMessageError]');
        </script>
    }
</body>
</html>