OnlineStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core.Contracts;
using OnlineStore.Infrastructure.Data.Models;
using static OnlineStore.Core.Constants.MessageConstants;

namespace OnlineStore.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService cartService;
        private readonly IComicService comicService;

        public CartController(ICartService cartService,
            IComicService comicService)
        {
            this.cartService = cartService;
            this.comicService = comicService;
        }

        public async Task<IActionResult> Details()
        {
            Cart cart = new Cart();

            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            cart = await cartService.GetCartByUserId(email);

            return View(cart);
        }

        public async Task<IActionResult> Purchase(int id)
        {
            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            var comic = await comicService.ComicExistsAsync(id);

            if(!comic)
            {
                TempData[UserMessageError] = "Such comic does not exist!";

                return RedirectToAction("All", "Comic");
            }

            Cart cart = await cartService.GetCartByUserId(email);

            var comicInCart = await cartService.ComicExistsInCart(cart, id);

            if (comicInCart)
            {
                TempData[UserMessageError] = "Comic already in cart!";

                return RedirectToAction("All", "Comic");
            }
            await cartService.Add(cart, id);

            TempData[UserMessageSuccess] = "Comic added to cart!";

            return RedirectToAction("All", "Comic");
        }

        public async Task<IActionResult> Remove(int id)
        {
            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            Cart cart = await cartService.GetCartByUserId(email);

            var comicInCart = await cartService.ComicExistsInCart(cart, id);

            if (!comicInCart)
            {
                TempData[UserMessageError] = "No such comic in the cart!";

                return RedirectToAction("All", "Comic");
            }

            await cartService.Remove(cart, id);

            TempData[UserMessageSuccess] = "Comic removed from cart!";

            return RedirectToAction("Details");
        }

        public async Task<IActionResult> Order(int id)
        {
            var email = GetEmail(this.User);

            if (email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Index", "Home");
            }

            var cartExist = await cartService.CartExists(id);

            if (!cartExist)
            {
                TempData[UserMessageError] = "No cart found!";

                return RedirectToAction("All", "Comic");
            }

            Cart cart = await cartService.GetCartByUserId(email);

            if(cart == null || cart.Id != id)
            {
                TempData[UserMessageError] = "No cart found!";
                
                return RedirectToAction("All", "Comic");
            }


            if (cart.Comics.Count == 0)
            {
                TempData[UserMessageError] = "No items in cart!";

                return RedirectToAction("All", "Comic");
            }

            await cartService.EmptyCart(cart.Id);

            TempData[UserMessageSuccess] = "Order completed!";

            return View();
        }

    }
}

OnlineStore/Controllers/ComicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core.Contracts;
using OnlineStore.Core.Models.Category;
using OnlineStore.Core.Models.Comic;
using OnlineStore.Infrastructure.Data.Models;
using static OnlineStore.Core.Constants.MessageConstants;

namespace OnlineStore.Controllers
{
    public class ComicController : BaseController
    {
        private ICreatorService creatorService;
        private IComicService comicService;
        private ICategoryService categoryService;
        private IReviewService reviewService;

        public ComicController(ICreatorService creatorService,
                    IComicService comicService, 
                    ICategoryService categoryService,
                    IReviewService reviewService)
        {
            this.creatorService = creatorService;
            this.comicService = comicService;
            this.categoryService = categoryService;
            this.reviewService = reviewService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] ComicAllQueryModel query)
        {
            AllComicsFilteredAndOrdered model = await comicService.AllAsync(query);

            query.Comics = model.Comics;
            query.TotalComics = model.TotalComicsCount;
            query.Categories = await categoryService.AllCategoryNames();

            return View(query);
        }

        
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            ComicDetailsViewModel model = new ComicDetailsViewModel();

            model = await comicService.GetComicAsync(model, id);

            if(model == null)
            {
                TempData[UserMessageError] = "Comic does not exist!";

                return RedirectToAction("All");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            AddComicViewModel viewModel = new AddComicViewModel();

            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            viewModel.Categories = categories;

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddComicViewModel model)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            model.Categories = categories;

            if (!await creatorService.ValidateCreator(model.Creator))
            {
                ModelState.AddModelError(nameof(model.Creator), "Creator does not exist in database! Please add the creator, before the comic!");

                return View(model);
            }

            if (!ModelState.IsValid)
            {
                TempData[UserMessageError] = "Invalid comic data!";

                return View(model);
            }

            Creator creator = await creatorService.GetCreatorByNameAsync(model.Creator);
            await comicService.AddComicAsync(model, creator);

            TempData[UserMessageSuccess] = "Comic added succesfully!";

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }
            bool result = await comicService.DeleteComic(id);

            if (result)
            {
                TempData[UserMessageSuccess] = "Comic deleted succesfully!";

                return RedirectToAction("All");
            }
            else
            {
                TempData[UserMessageError] = "Comic does not exist!";

                return RedirectToAction("All");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            AddComicViewModel model = new AddComicViewModel();

            model = comicService.FindComic(id);

           if (model == null)
            {
                TempData[UserMessageError] = "Comic does not exist!";
                return RedirectToAction("All");
            }

            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            model.Categories = categories;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddComicViewModel model)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            var comic = comicService.FindComic(id);
            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            if (comic == null)
            {
                return RedirectToAction("All");
            }

            if (!await creatorService.ValidateCreator(model.Creator))
            {
                ModelState.AddModelError(nameof(model.Creator), "Creator does not exist in database! Please add the creator, before you can proceed.");

                model.Categories = categories;

                return View(model);
            }

            await comicService.EditComicAsync(model, id);

            TempData[UserMessageSuccess] = "Comic edited succesfully!";

            return RedirectToAction("All");
        }
    }
}

OnlineStore/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core.Contracts;
using OnlineStore.Core.Models.Reviews;
using OnlineStore.Infrastructure.Data.Models;
using System.Security.Claims;
using static OnlineStore.Core.Constants.MessageConstants;

namespace OnlineStore.Controllers
{
    public class ReviewController : BaseController
    {
        private IReviewService reviewService;
        private IComicService comicService;

        public ReviewController(IReviewService reviewService,
            IComicService comicService)
        {
            this.reviewService = reviewService;
            this.comicService = comicService;
        }

        [HttpGet]
        public IActionResult Add(int id)
        {
            string? userId = GetId(User);
            string? email = GetEmail(User);

            if (userId == null || email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("All", "Comic");
            }
            
            if(!comicService.ComicExistsAsync(id).Result)
            {
                TempData[UserMessageError] = "Comic not found!";

                return RedirectToAction("All", "Comic");
            }

            ReviewAddFormModel form = new ReviewAddFormModel();
            

            form.ReviewerId = userId;
            form.ReviewerName = email;
            form.ComicId = id;

            ViewBag.Id = id;
            ViewBag.ReviewerId = userId;
            ViewBag.ReviewerName = email;

            return View(form);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ReviewAddFormModel form, int id)
        {

            string? userId = GetId(User);
            string? email = GetEmail(User);

            if (userId == null || email == null)
            {
                TempData[UserMessageError] = "No user found!";

                return RedirectToAction("Details", "Comic", new { id });
            }

            if (!comicService.ComicExistsAsync(id).Result)
            {
                TempData[UserMessageError] = "Comic not found!";

                return RedirectToAction("All", "Comic");
            }

            form.ReviewerId = userId;
            form.ReviewerName = email;
            form.ComicId = id;

            await reviewService.Add(form);

            TempData[UserMessageSuccess] = "Review added succesfully!";

            return RedirectToAction("Details", "Comic", new { id });
        }

        public async Task<IActionResult> Remove(string id)
        {
            var reviewId = Guid.Parse(id);

            var review = await reviewService.FindReviewAsync(reviewId);

            if (review == null)
            {
                TempData[UserMessageError] = "No review found!";

                return RedirectToAction("All", "Comic");
            }

            if(review.ReviewerId.ToString() != GetId(User) && !IsAdmin(User))
            {
                TempData[UserMessageError] = "You have no permission to remove the review!";

                return RedirectToAction("All", "Comic");
            }

            await reviewService.RemoveAsync(reviewId);

            TempData[UserMessageSuccess] = "Review removed succesfully!";

            return RedirectToAction("All", "Comic");
        }
    }
}

OnlineStore/Views/Comic/Add.cshtml
@model AddComicViewModel
@using OnlineStore.Core.Models.Comic;

@{
    ViewData["Title"] = "Add Comic";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<partial name="_ComicFormPartial" model="@Model" />

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
}

OnlineStore/Views/Comic/All.cshtml
@model ComicAllQueryModel
@using OnlineStore.Core.Models.Comic;

@{
    ViewBag.Title = "All Comics";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form method="get">
    <div class="row">
        <div class="form-group col-md-3 d-flex justify-content-between">
            <div class="form-group">
                <label asp-for="CategoryName"></label>
                <select asp-for="CategoryName" class="form-control">
                    <option value="">All</option>
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category">@category</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group col-md-3">
            <label asp-for="SearchString"></label>
            <input asp-for="SearchString" class="form-control" placeholder="...">
        </div>

        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="ComicSorting"></label>
                <select asp-for="ComicSorting" class="form-control">
                    <option value="0">Price Ascending</option>
                    <option value="1">Price Descending</option>
                    <option value="2">Alphabetically</option>
                    <option value="3">Alphabetically Descending</option>
                    <option value="4">By Author Alphabetically</option>
                    <option value="5">By Author Alphabetically Descending</option>
                </select>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group mt-4 p-2">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


@{
    int previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    int maxPage = (int)Math.Ceiling((double)Model.TotalComics /
        Model.ComicsPerPage);
}

<div class="row mb-5">
    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Comic"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-category="@Model.CategoryName"
           asp-route-searchTerm="@Model.SearchString"
           asp-route-sorting="@((int)Model.ComicSorting)"><<</a>
    </div>

    @{
        bool shouldNextPageBeDisabled = Model.CurrentPage == maxPage ||
        !Model.Comics.Any();
    }

    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary
           @(shouldNextPageBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Comic"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-category="@Model.CategoryName"
           asp-route-searchTerm="@Model.SearchString"
           asp-route-sorting="@((int)Model.ComicSorting)">>></a>
    </div>
</div>

@if (!Model.Comics.Any())
{
    <h2 class="text-center">No comics found by the given criteria!</h2>
}

<div class="row">
    @foreach (var comic in Model.Comics)
    {
        if (!comic.IsDeleted)
        {
            <partial name="_ComicDetailsPartial" model="@comic" />
        }
    }
</div>

OnlineStore/Views/Comic/Details.cshtml
@model ComicDetailsViewModel
@using OnlineStore.Core.Models.Comic
@using OnlineStore.Infrastructure.Data.Models;

@{
    ViewBag.Title = "Comic Details";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="container" style="display:inline">
    <div class="row">
        <div class="col-4">
            <img class="card-img-top" style="width: 20rem;"
                 src="@Model.PhotoUrl" alt="Comic Image">
        </div>
        <div class="card col-8 border-0">
            <p style="font-size:25px;"><u>@Model.Title</u></p>
            <p>Created by: <b>@Model.CreatorName</b></p>
            <p>Category: <b>@Model.CategoryName</b></p>
            <p>@Model.Description</p>
            <div class="form-inline">
                @if (this.User.Identity?.IsAuthenticated ?? false)
                {
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a class="btn btn-warning" asp-controller="Comic" asp-action="Edit"
                           asp-route-id="@Model.Id">Edit</a>
                        <a class="ml-2 btn btn-danger" asp-controller="Comic" asp-action="Delete"
                           asp-route-id="@Model.Id" confirm="Are your sure?">Delete</a>
                    }
                    <a class="ml-2 btn btn-info" asp-controller="Creator" asp-action="Details"
                       asp-route-id="@Model.CreatorId">View Creator</a>
                    <a class="ml-2 btn btn-success" asp-controller="Cart" asp-action="Purchase"
                       asp-route-id="@Model.Id">Add to Cart</a>
                }
            </div>
            <p></p>
            <div class="form-inline align-self-center">
                <p text-centre style="font-size:25px;"><u>Reviews</u></p>
                <a class="ml-2 btn btn-info" asp-controller="Review" asp-action="Add"
                   asp-route-id="@Model.Id">Write a Review</a>
            </div>

            @if (Model.Reviews.Count == 0)
            {
                <p text-centre style="font-size:25px;">No reviews yet!</p>
            }

            @foreach(Review review in Model.Reviews)
            {
                <br />
                <div class="form-inline align-self-center card col-8 border-1">
                    <p style="font-size:15px;"><b>@review.ReviewText</b></p>
                    <p>Written by: <b>@review.ReviewerName</b></p>
                    <p>Rating: <b>@review.StarRating/5</b></p>
                    @{
                        if (review.ReviewerName == User.Identity.Name || User.IsInRole("Admin"))
                        {
                            <div class="form-inline align-self-center">
                                <a class="btn btn-danger" asp-controller="Review" asp-action="Remove"
                                   asp-route-id="@review.Id" confirm="Are your sure?">Remove</a>
                            </div>
                        }
                    }
                </div>
            }
        </div>
    </div>
</div>

OnlineStore/Views/Comic/Edit.cshtml
@model AddComicViewModel
@using OnlineStore.Core.Models.Comic;

@{
    ViewData["Title"] = "Edit Comic";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<partial name="_ComicFormPartial" model="@Model" />

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
}