OnlineStore/Controllers/ComicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core.Contracts;
using OnlineStore.Core.Models.Category;
using OnlineStore.Core.Models.Comic;
using OnlineStore.Infrastructure.Data.Models;
using static OnlineStore.Core.Constants.MessageConstants;

namespace OnlineStore.Controllers
{
    public class ComicController : BaseController
    {
        private ICreatorService creatorService;
        private IComicService comicService;
        private ICategoryService categoryService;
        private IReviewService reviewService;

        public ComicController(ICreatorService creatorService,
                    IComicService comicService, 
                    ICategoryService categoryService,
                    IReviewService reviewService)
        {
            this.creatorService = creatorService;
            this.comicService = comicService;
            this.categoryService = categoryService;
            this.reviewService = reviewService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] ComicAllQueryModel query)
        {
            AllComicsFilteredAndOrdered model = await comicService.AllAsync(query);

            query.Comics = model.Comics;
            query.TotalComics = model.TotalComicsCount;
            query.Categories = await categoryService.AllCategoryNames();

            return View(query);
        }

        
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            ComicDetailsViewModel model = new ComicDetailsViewModel();

            model = await comicService.GetComicAsync(model, id);

            if(model == null)
            {
                TempData[UserMessageError] = "Comic does not exist!";

                return RedirectToAction("All");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            AddComicViewModel viewModel = new AddComicViewModel();

            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            viewModel.Categories = categories;

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddComicViewModel model)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            model.Categories = categories;

            if (!await creatorService.ValidateCreator(model.Creator))
            {
                ModelState.AddModelError(nameof(model.Creator), "Creator does not exist in database! Please add the creator, before the comic!");

                return View(model);
            }

            if (!ModelState.IsValid)
            {
                TempData[UserMessageError] = "Invalid comic data!";

                return View(model);
            }

            Creator creator = await creatorService.GetCreatorByNameAsync(model.Creator);
            await comicService.AddComicAsync(model, creator);

            TempData[UserMessageSuccess] = "Comic added succesfully!";

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }
            bool result = await comicService.DeleteComic(id);

            if (result)
            {
                TempData[UserMessageSuccess] = "Comic deleted succesfully!";

                return RedirectToAction("All");
            }
            else
            {
                TempData[UserMessageError] = "Comic does not exist!";

                return RedirectToAction("All");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            AddComicViewModel model = new AddComicViewModel();

            model = comicService.FindComic(id);

           if (model == null)
            {
                TempData[UserMessageError] = "Comic does not exist!";
                return RedirectToAction("All");
            }

            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            model.Categories = categories;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddComicViewModel model)
        {
            if (!IsAdmin(User))
            {
                return Unauthorized();
            }

            var comic = comicService.FindComic(id);
            IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesAsync();

            if (comic == null)
            {
                return RedirectToAction("All");
            }

            if (!await creatorService.ValidateCreator(model.Creator))
            {
                ModelState.AddModelError(nameof(model.Creator), "Creator does not exist in database! Please add the creator, before you can proceed.");

                model.Categories = categories;

                return View(model);
            }

            await comicService.EditComicAsync(model, id);

            TempData[UserMessageSuccess] = "Comic edited succesfully!";

            return RedirectToAction("All");
        }
    }
}

OnlineStore/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using OnlineStore.Core.Constants;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Panel</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OnlineStore - <a asp-area="" asp-controller="Comic" asp-action="All">All Comics</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if (TempData[MessageConstants.UserMessageSuccess] != null)
    {
        <script defer>
            message.showSuccess('@TempData[MessageConstants.UserMessageSuccess]');
        </script>
    }
    @if (TempData[MessageConstants.UserMessageError] != null)
    {
        <script defer>
            message.showError('@TempData[MessageConstants.UserMessageError]');
        </script>
    }
</body>
</html>